[package]
name = "memalloc"
version = "0.1.0"
authors = ["Mike Krinkin <krinkin.m.u@gmail.com>"]
edition = "2018"

[lib]
name = "memalloc"
crate-type = ["rlib"]

[dependencies]
bootstrap = { path = "../bootstrap" }
