[package]
name = "memory"
version = "0.1.0"
authors = ["Mike Krinkin <krinkin.m.u@gmail.com>"]
edition = "2018"

[lib]
name = "memory"
crate-type = ["rlib"]

[dependencies]
intrusive = { path = "../intrusive" }
numeric = { path = "../numeric" }
sync = { path = "../sync" }
