[workspace]
members = [
    "bootstrap",
    "devicetree",
    "interrupt",
    "kernel",
    "memalloc",
    "pl011",
    "runtime",
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

