[workspace]
members = [
    "bootstrap",
    "devicetree",
    "interrupt",
    "kernel",
    "log",
    "memory",
    "numeric",
    "pl011",
    "runtime",
    "sync",
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

